on:
  # schedule:
  #   - cron: "30 2 * * *"
  workflow_dispatch:
jobs:
  auto-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.AUTOVERSION_TOKEN }}
          EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_NAME: github-actions[bot]
        run: ./bin/make autoversion
